### ISSUE TITLE
Admin - let's talk form: Form description won't display in front end.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Paradise-Pools#2]
![image](https://cloud.githubusercontent.com/assets/11186313/10239021/a37113f2-68f9-11e5-969a-91c0508606f1.png)

**Comment by ganesh-titan** [comment]
![screen shot 2015-10-12 at 09 20 23](https://cloud.githubusercontent.com/assets/13450883/10421275/e2414bd0-70c2-11e5-8922-a665a5934e50.png)

**Comment by ganesh-titan** [comment]
![screen shot 2015-10-12 at 09 20 23](https://cloud.githubusercontent.com/assets/13450883/10421288/2a4931ae-70c3-11e5-8d34-920f70cc9563.png)

**Comment by ganesh-titan** [comment]
FYI : Go to titan options and change the label false to true then it's appears description in front end.

**Comment by roseliesromeo** [comment]
Thanks for the info.

However, let's keep in mind that we can't expect users to do that (change parameter in the short code) especially there is no user guide attached.
