### ISSUE TITLE
Header section: Phone is top aligned in front end but it is almost vertically centered in the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Paradise-Pools#25]
![image](https://cloud.githubusercontent.com/assets/11186313/10241407/1d954e2a-691b-11e5-9ca6-b8df78eb00a2.png)

**Comment by roseliesromeo** [comment]
Can we have centered within the menu bar?

**Comment by ganesh-titan** [comment]
Phone Icon updated ( vertically centered ).
